name: Deploy Angular SPA to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production --base-href=""
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: /